// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_flightdeck

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func FlightdeckProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description: "A Terraform provider for Flightdeck",
	}
}

type FlightdeckModel struct {
}
