// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_identity_provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func IdentityProviderResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time of the resources creation.",
				MarkdownDescription: "The date and time of the resources creation.",
			},
			"github": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"api_url": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The API URL of the Github application.",
						MarkdownDescription: "The API URL of the Github application.",
					},
					"base_url": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The base URL of the Github application.",
						MarkdownDescription: "The base URL of the Github application.",
					},
					"client_id": schema.StringAttribute{
						Required:            true,
						Description:         "The client ID of the Github application.",
						MarkdownDescription: "The client ID of the Github application.",
					},
					"client_secret": schema.StringAttribute{
						Required:            true,
						Sensitive:           true,
						Description:         "The client secret of the Github application.",
						MarkdownDescription: "The client secret of the Github application.",
					},
					"config_type": schema.StringAttribute{
						Required:            true,
						Description:         "The type of Identity Provider configuration.",
						MarkdownDescription: "The type of Identity Provider configuration.",
					},
					"redirect_uri": schema.StringAttribute{
						Required:            true,
						Description:         "The URI to redirect to after the user has authenticated.",
						MarkdownDescription: "The URI to redirect to after the user has authenticated.",
					},
				},
				CustomType: GithubType{
					ObjectType: types.ObjectType{
						AttrTypes: GithubValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"gitlab": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"client_id": schema.StringAttribute{
						Required:            true,
						Description:         "The client ID of the Gitlab application.",
						MarkdownDescription: "The client ID of the Gitlab application.",
					},
					"client_secret": schema.StringAttribute{
						Required:            true,
						Sensitive:           true,
						Description:         "The client secret of the Gitlab application.",
						MarkdownDescription: "The client secret of the Gitlab application.",
					},
					"config_type": schema.StringAttribute{
						Required:            true,
						Description:         "The type of Identity Provider configuration.",
						MarkdownDescription: "The type of Identity Provider configuration.",
					},
					"redirect_uri": schema.StringAttribute{
						Required:            true,
						Description:         "The URI to redirect to after the user has authenticated.",
						MarkdownDescription: "The URI to redirect to after the user has authenticated.",
					},
				},
				CustomType: GitlabType{
					ObjectType: types.ObjectType{
						AttrTypes: GitlabValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"google": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"client_id": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The client ID of the Google application.",
						MarkdownDescription: "The client ID of the Google application.",
					},
					"client_secret": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Sensitive:           true,
						Description:         "The client secret of the Google application.",
						MarkdownDescription: "The client secret of the Google application.",
					},
					"config_type": schema.StringAttribute{
						Required:            true,
						Description:         "The type of Identity Provider configuration.",
						MarkdownDescription: "The type of Identity Provider configuration.",
					},
					"hosted_domain": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The hosted domain of the Google application.",
						MarkdownDescription: "The hosted domain of the Google application.",
					},
					"redirect_uri": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The URI to redirect to after the user has authenticated.",
						MarkdownDescription: "The URI to redirect to after the user has authenticated.",
					},
					"refresh_token": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Whether to refresh the token of the Google application.",
						MarkdownDescription: "Whether to refresh the token of the Google application.",
					},
					"user_ip": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The user IP of the Google application.",
						MarkdownDescription: "The user IP of the Google application.",
					},
				},
				CustomType: GoogleType{
					ObjectType: types.ObjectType{
						AttrTypes: GoogleValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Flightdeck resource.",
				MarkdownDescription: "The ID of the Flightdeck resource.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Flightdeck Identity Provider resource.",
				MarkdownDescription: "The name of the Flightdeck Identity Provider resource.",
			},
			"organization_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Flightdeck Organization resource.",
				MarkdownDescription: "The ID of the Flightdeck Organization resource.",
			},
			"tenant_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Flightdeck Tenant resource.",
				MarkdownDescription: "The name of the Flightdeck Tenant resource.",
			},
		},
		Description: "Represents a Flightdeck Identity Provider resource.",
	}
}

type IdentityProviderModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	Github         GithubValue  `tfsdk:"github"`
	Gitlab         GitlabValue  `tfsdk:"gitlab"`
	Google         GoogleValue  `tfsdk:"google"`
	Id             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	OrganizationId types.String `tfsdk:"organization_id"`
	TenantName     types.String `tfsdk:"tenant_name"`
}

var _ basetypes.ObjectTypable = GithubType{}

type GithubType struct {
	basetypes.ObjectType
}

func (t GithubType) Equal(o attr.Type) bool {
	other, ok := o.(GithubType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t GithubType) String() string {
	return "GithubType"
}

func (t GithubType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	apiUrlAttribute, ok := attributes["api_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_url is missing from object`)

		return nil, diags
	}

	apiUrlVal, ok := apiUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_url expected to be basetypes.StringValue, was: %T`, apiUrlAttribute))
	}

	baseUrlAttribute, ok := attributes["base_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`base_url is missing from object`)

		return nil, diags
	}

	baseUrlVal, ok := baseUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`base_url expected to be basetypes.StringValue, was: %T`, baseUrlAttribute))
	}

	clientIdAttribute, ok := attributes["client_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_id is missing from object`)

		return nil, diags
	}

	clientIdVal, ok := clientIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_id expected to be basetypes.StringValue, was: %T`, clientIdAttribute))
	}

	clientSecretAttribute, ok := attributes["client_secret"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret is missing from object`)

		return nil, diags
	}

	clientSecretVal, ok := clientSecretAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret expected to be basetypes.StringValue, was: %T`, clientSecretAttribute))
	}

	configTypeAttribute, ok := attributes["config_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_type is missing from object`)

		return nil, diags
	}

	configTypeVal, ok := configTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_type expected to be basetypes.StringValue, was: %T`, configTypeAttribute))
	}

	redirectUriAttribute, ok := attributes["redirect_uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`redirect_uri is missing from object`)

		return nil, diags
	}

	redirectUriVal, ok := redirectUriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`redirect_uri expected to be basetypes.StringValue, was: %T`, redirectUriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return GithubValue{
		ApiUrl:       apiUrlVal,
		BaseUrl:      baseUrlVal,
		ClientId:     clientIdVal,
		ClientSecret: clientSecretVal,
		ConfigType:   configTypeVal,
		RedirectUri:  redirectUriVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewGithubValueNull() GithubValue {
	return GithubValue{
		state: attr.ValueStateNull,
	}
}

func NewGithubValueUnknown() GithubValue {
	return GithubValue{
		state: attr.ValueStateUnknown,
	}
}

func NewGithubValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (GithubValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing GithubValue Attribute Value",
				"While creating a GithubValue value, a missing attribute value was detected. "+
					"A GithubValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("GithubValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid GithubValue Attribute Type",
				"While creating a GithubValue value, an invalid attribute value was detected. "+
					"A GithubValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("GithubValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("GithubValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra GithubValue Attribute Value",
				"While creating a GithubValue value, an extra attribute value was detected. "+
					"A GithubValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra GithubValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewGithubValueUnknown(), diags
	}

	apiUrlAttribute, ok := attributes["api_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_url is missing from object`)

		return NewGithubValueUnknown(), diags
	}

	apiUrlVal, ok := apiUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_url expected to be basetypes.StringValue, was: %T`, apiUrlAttribute))
	}

	baseUrlAttribute, ok := attributes["base_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`base_url is missing from object`)

		return NewGithubValueUnknown(), diags
	}

	baseUrlVal, ok := baseUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`base_url expected to be basetypes.StringValue, was: %T`, baseUrlAttribute))
	}

	clientIdAttribute, ok := attributes["client_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_id is missing from object`)

		return NewGithubValueUnknown(), diags
	}

	clientIdVal, ok := clientIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_id expected to be basetypes.StringValue, was: %T`, clientIdAttribute))
	}

	clientSecretAttribute, ok := attributes["client_secret"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret is missing from object`)

		return NewGithubValueUnknown(), diags
	}

	clientSecretVal, ok := clientSecretAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret expected to be basetypes.StringValue, was: %T`, clientSecretAttribute))
	}

	configTypeAttribute, ok := attributes["config_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_type is missing from object`)

		return NewGithubValueUnknown(), diags
	}

	configTypeVal, ok := configTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_type expected to be basetypes.StringValue, was: %T`, configTypeAttribute))
	}

	redirectUriAttribute, ok := attributes["redirect_uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`redirect_uri is missing from object`)

		return NewGithubValueUnknown(), diags
	}

	redirectUriVal, ok := redirectUriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`redirect_uri expected to be basetypes.StringValue, was: %T`, redirectUriAttribute))
	}

	if diags.HasError() {
		return NewGithubValueUnknown(), diags
	}

	return GithubValue{
		ApiUrl:       apiUrlVal,
		BaseUrl:      baseUrlVal,
		ClientId:     clientIdVal,
		ClientSecret: clientSecretVal,
		ConfigType:   configTypeVal,
		RedirectUri:  redirectUriVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewGithubValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) GithubValue {
	object, diags := NewGithubValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewGithubValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t GithubType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewGithubValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewGithubValueUnknown(), nil
	}

	if in.IsNull() {
		return NewGithubValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewGithubValueMust(GithubValue{}.AttributeTypes(ctx), attributes), nil
}

func (t GithubType) ValueType(ctx context.Context) attr.Value {
	return GithubValue{}
}

var _ basetypes.ObjectValuable = GithubValue{}

type GithubValue struct {
	ApiUrl       basetypes.StringValue `tfsdk:"api_url"`
	BaseUrl      basetypes.StringValue `tfsdk:"base_url"`
	ClientId     basetypes.StringValue `tfsdk:"client_id"`
	ClientSecret basetypes.StringValue `tfsdk:"client_secret"`
	ConfigType   basetypes.StringValue `tfsdk:"config_type"`
	RedirectUri  basetypes.StringValue `tfsdk:"redirect_uri"`
	state        attr.ValueState
}

func (v GithubValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["api_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["base_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["client_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["client_secret"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["config_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["redirect_uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.ApiUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["api_url"] = val

		val, err = v.BaseUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["base_url"] = val

		val, err = v.ClientId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_id"] = val

		val, err = v.ClientSecret.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_secret"] = val

		val, err = v.ConfigType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["config_type"] = val

		val, err = v.RedirectUri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["redirect_uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v GithubValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v GithubValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v GithubValue) String() string {
	return "GithubValue"
}

func (v GithubValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"api_url":       basetypes.StringType{},
		"base_url":      basetypes.StringType{},
		"client_id":     basetypes.StringType{},
		"client_secret": basetypes.StringType{},
		"config_type":   basetypes.StringType{},
		"redirect_uri":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"api_url":       v.ApiUrl,
			"base_url":      v.BaseUrl,
			"client_id":     v.ClientId,
			"client_secret": v.ClientSecret,
			"config_type":   v.ConfigType,
			"redirect_uri":  v.RedirectUri,
		})

	return objVal, diags
}

func (v GithubValue) Equal(o attr.Value) bool {
	other, ok := o.(GithubValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ApiUrl.Equal(other.ApiUrl) {
		return false
	}

	if !v.BaseUrl.Equal(other.BaseUrl) {
		return false
	}

	if !v.ClientId.Equal(other.ClientId) {
		return false
	}

	if !v.ClientSecret.Equal(other.ClientSecret) {
		return false
	}

	if !v.ConfigType.Equal(other.ConfigType) {
		return false
	}

	if !v.RedirectUri.Equal(other.RedirectUri) {
		return false
	}

	return true
}

func (v GithubValue) Type(ctx context.Context) attr.Type {
	return GithubType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v GithubValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"api_url":       basetypes.StringType{},
		"base_url":      basetypes.StringType{},
		"client_id":     basetypes.StringType{},
		"client_secret": basetypes.StringType{},
		"config_type":   basetypes.StringType{},
		"redirect_uri":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = GitlabType{}

type GitlabType struct {
	basetypes.ObjectType
}

func (t GitlabType) Equal(o attr.Type) bool {
	other, ok := o.(GitlabType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t GitlabType) String() string {
	return "GitlabType"
}

func (t GitlabType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	clientIdAttribute, ok := attributes["client_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_id is missing from object`)

		return nil, diags
	}

	clientIdVal, ok := clientIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_id expected to be basetypes.StringValue, was: %T`, clientIdAttribute))
	}

	clientSecretAttribute, ok := attributes["client_secret"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret is missing from object`)

		return nil, diags
	}

	clientSecretVal, ok := clientSecretAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret expected to be basetypes.StringValue, was: %T`, clientSecretAttribute))
	}

	configTypeAttribute, ok := attributes["config_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_type is missing from object`)

		return nil, diags
	}

	configTypeVal, ok := configTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_type expected to be basetypes.StringValue, was: %T`, configTypeAttribute))
	}

	redirectUriAttribute, ok := attributes["redirect_uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`redirect_uri is missing from object`)

		return nil, diags
	}

	redirectUriVal, ok := redirectUriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`redirect_uri expected to be basetypes.StringValue, was: %T`, redirectUriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return GitlabValue{
		ClientId:     clientIdVal,
		ClientSecret: clientSecretVal,
		ConfigType:   configTypeVal,
		RedirectUri:  redirectUriVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewGitlabValueNull() GitlabValue {
	return GitlabValue{
		state: attr.ValueStateNull,
	}
}

func NewGitlabValueUnknown() GitlabValue {
	return GitlabValue{
		state: attr.ValueStateUnknown,
	}
}

func NewGitlabValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (GitlabValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing GitlabValue Attribute Value",
				"While creating a GitlabValue value, a missing attribute value was detected. "+
					"A GitlabValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("GitlabValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid GitlabValue Attribute Type",
				"While creating a GitlabValue value, an invalid attribute value was detected. "+
					"A GitlabValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("GitlabValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("GitlabValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra GitlabValue Attribute Value",
				"While creating a GitlabValue value, an extra attribute value was detected. "+
					"A GitlabValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra GitlabValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewGitlabValueUnknown(), diags
	}

	clientIdAttribute, ok := attributes["client_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_id is missing from object`)

		return NewGitlabValueUnknown(), diags
	}

	clientIdVal, ok := clientIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_id expected to be basetypes.StringValue, was: %T`, clientIdAttribute))
	}

	clientSecretAttribute, ok := attributes["client_secret"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret is missing from object`)

		return NewGitlabValueUnknown(), diags
	}

	clientSecretVal, ok := clientSecretAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret expected to be basetypes.StringValue, was: %T`, clientSecretAttribute))
	}

	configTypeAttribute, ok := attributes["config_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_type is missing from object`)

		return NewGitlabValueUnknown(), diags
	}

	configTypeVal, ok := configTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_type expected to be basetypes.StringValue, was: %T`, configTypeAttribute))
	}

	redirectUriAttribute, ok := attributes["redirect_uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`redirect_uri is missing from object`)

		return NewGitlabValueUnknown(), diags
	}

	redirectUriVal, ok := redirectUriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`redirect_uri expected to be basetypes.StringValue, was: %T`, redirectUriAttribute))
	}

	if diags.HasError() {
		return NewGitlabValueUnknown(), diags
	}

	return GitlabValue{
		ClientId:     clientIdVal,
		ClientSecret: clientSecretVal,
		ConfigType:   configTypeVal,
		RedirectUri:  redirectUriVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewGitlabValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) GitlabValue {
	object, diags := NewGitlabValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewGitlabValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t GitlabType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewGitlabValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewGitlabValueUnknown(), nil
	}

	if in.IsNull() {
		return NewGitlabValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewGitlabValueMust(GitlabValue{}.AttributeTypes(ctx), attributes), nil
}

func (t GitlabType) ValueType(ctx context.Context) attr.Value {
	return GitlabValue{}
}

var _ basetypes.ObjectValuable = GitlabValue{}

type GitlabValue struct {
	ClientId     basetypes.StringValue `tfsdk:"client_id"`
	ClientSecret basetypes.StringValue `tfsdk:"client_secret"`
	ConfigType   basetypes.StringValue `tfsdk:"config_type"`
	RedirectUri  basetypes.StringValue `tfsdk:"redirect_uri"`
	state        attr.ValueState
}

func (v GitlabValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["client_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["client_secret"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["config_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["redirect_uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.ClientId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_id"] = val

		val, err = v.ClientSecret.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_secret"] = val

		val, err = v.ConfigType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["config_type"] = val

		val, err = v.RedirectUri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["redirect_uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v GitlabValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v GitlabValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v GitlabValue) String() string {
	return "GitlabValue"
}

func (v GitlabValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"client_id":     basetypes.StringType{},
		"client_secret": basetypes.StringType{},
		"config_type":   basetypes.StringType{},
		"redirect_uri":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"client_id":     v.ClientId,
			"client_secret": v.ClientSecret,
			"config_type":   v.ConfigType,
			"redirect_uri":  v.RedirectUri,
		})

	return objVal, diags
}

func (v GitlabValue) Equal(o attr.Value) bool {
	other, ok := o.(GitlabValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ClientId.Equal(other.ClientId) {
		return false
	}

	if !v.ClientSecret.Equal(other.ClientSecret) {
		return false
	}

	if !v.ConfigType.Equal(other.ConfigType) {
		return false
	}

	if !v.RedirectUri.Equal(other.RedirectUri) {
		return false
	}

	return true
}

func (v GitlabValue) Type(ctx context.Context) attr.Type {
	return GitlabType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v GitlabValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"client_id":     basetypes.StringType{},
		"client_secret": basetypes.StringType{},
		"config_type":   basetypes.StringType{},
		"redirect_uri":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = GoogleType{}

type GoogleType struct {
	basetypes.ObjectType
}

func (t GoogleType) Equal(o attr.Type) bool {
	other, ok := o.(GoogleType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t GoogleType) String() string {
	return "GoogleType"
}

func (t GoogleType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	clientIdAttribute, ok := attributes["client_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_id is missing from object`)

		return nil, diags
	}

	clientIdVal, ok := clientIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_id expected to be basetypes.StringValue, was: %T`, clientIdAttribute))
	}

	clientSecretAttribute, ok := attributes["client_secret"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret is missing from object`)

		return nil, diags
	}

	clientSecretVal, ok := clientSecretAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret expected to be basetypes.StringValue, was: %T`, clientSecretAttribute))
	}

	configTypeAttribute, ok := attributes["config_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_type is missing from object`)

		return nil, diags
	}

	configTypeVal, ok := configTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_type expected to be basetypes.StringValue, was: %T`, configTypeAttribute))
	}

	hostedDomainAttribute, ok := attributes["hosted_domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hosted_domain is missing from object`)

		return nil, diags
	}

	hostedDomainVal, ok := hostedDomainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hosted_domain expected to be basetypes.StringValue, was: %T`, hostedDomainAttribute))
	}

	redirectUriAttribute, ok := attributes["redirect_uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`redirect_uri is missing from object`)

		return nil, diags
	}

	redirectUriVal, ok := redirectUriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`redirect_uri expected to be basetypes.StringValue, was: %T`, redirectUriAttribute))
	}

	refreshTokenAttribute, ok := attributes["refresh_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`refresh_token is missing from object`)

		return nil, diags
	}

	refreshTokenVal, ok := refreshTokenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`refresh_token expected to be basetypes.BoolValue, was: %T`, refreshTokenAttribute))
	}

	userIpAttribute, ok := attributes["user_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_ip is missing from object`)

		return nil, diags
	}

	userIpVal, ok := userIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_ip expected to be basetypes.BoolValue, was: %T`, userIpAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return GoogleValue{
		ClientId:     clientIdVal,
		ClientSecret: clientSecretVal,
		ConfigType:   configTypeVal,
		HostedDomain: hostedDomainVal,
		RedirectUri:  redirectUriVal,
		RefreshToken: refreshTokenVal,
		UserIp:       userIpVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewGoogleValueNull() GoogleValue {
	return GoogleValue{
		state: attr.ValueStateNull,
	}
}

func NewGoogleValueUnknown() GoogleValue {
	return GoogleValue{
		state: attr.ValueStateUnknown,
	}
}

func NewGoogleValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (GoogleValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing GoogleValue Attribute Value",
				"While creating a GoogleValue value, a missing attribute value was detected. "+
					"A GoogleValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("GoogleValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid GoogleValue Attribute Type",
				"While creating a GoogleValue value, an invalid attribute value was detected. "+
					"A GoogleValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("GoogleValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("GoogleValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra GoogleValue Attribute Value",
				"While creating a GoogleValue value, an extra attribute value was detected. "+
					"A GoogleValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra GoogleValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewGoogleValueUnknown(), diags
	}

	clientIdAttribute, ok := attributes["client_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_id is missing from object`)

		return NewGoogleValueUnknown(), diags
	}

	clientIdVal, ok := clientIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_id expected to be basetypes.StringValue, was: %T`, clientIdAttribute))
	}

	clientSecretAttribute, ok := attributes["client_secret"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret is missing from object`)

		return NewGoogleValueUnknown(), diags
	}

	clientSecretVal, ok := clientSecretAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret expected to be basetypes.StringValue, was: %T`, clientSecretAttribute))
	}

	configTypeAttribute, ok := attributes["config_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_type is missing from object`)

		return NewGoogleValueUnknown(), diags
	}

	configTypeVal, ok := configTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_type expected to be basetypes.StringValue, was: %T`, configTypeAttribute))
	}

	hostedDomainAttribute, ok := attributes["hosted_domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hosted_domain is missing from object`)

		return NewGoogleValueUnknown(), diags
	}

	hostedDomainVal, ok := hostedDomainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hosted_domain expected to be basetypes.StringValue, was: %T`, hostedDomainAttribute))
	}

	redirectUriAttribute, ok := attributes["redirect_uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`redirect_uri is missing from object`)

		return NewGoogleValueUnknown(), diags
	}

	redirectUriVal, ok := redirectUriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`redirect_uri expected to be basetypes.StringValue, was: %T`, redirectUriAttribute))
	}

	refreshTokenAttribute, ok := attributes["refresh_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`refresh_token is missing from object`)

		return NewGoogleValueUnknown(), diags
	}

	refreshTokenVal, ok := refreshTokenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`refresh_token expected to be basetypes.BoolValue, was: %T`, refreshTokenAttribute))
	}

	userIpAttribute, ok := attributes["user_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_ip is missing from object`)

		return NewGoogleValueUnknown(), diags
	}

	userIpVal, ok := userIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_ip expected to be basetypes.BoolValue, was: %T`, userIpAttribute))
	}

	if diags.HasError() {
		return NewGoogleValueUnknown(), diags
	}

	return GoogleValue{
		ClientId:     clientIdVal,
		ClientSecret: clientSecretVal,
		ConfigType:   configTypeVal,
		HostedDomain: hostedDomainVal,
		RedirectUri:  redirectUriVal,
		RefreshToken: refreshTokenVal,
		UserIp:       userIpVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewGoogleValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) GoogleValue {
	object, diags := NewGoogleValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewGoogleValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t GoogleType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewGoogleValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewGoogleValueUnknown(), nil
	}

	if in.IsNull() {
		return NewGoogleValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewGoogleValueMust(GoogleValue{}.AttributeTypes(ctx), attributes), nil
}

func (t GoogleType) ValueType(ctx context.Context) attr.Value {
	return GoogleValue{}
}

var _ basetypes.ObjectValuable = GoogleValue{}

type GoogleValue struct {
	ClientId     basetypes.StringValue `tfsdk:"client_id"`
	ClientSecret basetypes.StringValue `tfsdk:"client_secret"`
	ConfigType   basetypes.StringValue `tfsdk:"config_type"`
	HostedDomain basetypes.StringValue `tfsdk:"hosted_domain"`
	RedirectUri  basetypes.StringValue `tfsdk:"redirect_uri"`
	RefreshToken basetypes.BoolValue   `tfsdk:"refresh_token"`
	UserIp       basetypes.BoolValue   `tfsdk:"user_ip"`
	state        attr.ValueState
}

func (v GoogleValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["client_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["client_secret"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["config_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["hosted_domain"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["redirect_uri"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["refresh_token"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["user_ip"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.ClientId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_id"] = val

		val, err = v.ClientSecret.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_secret"] = val

		val, err = v.ConfigType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["config_type"] = val

		val, err = v.HostedDomain.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hosted_domain"] = val

		val, err = v.RedirectUri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["redirect_uri"] = val

		val, err = v.RefreshToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["refresh_token"] = val

		val, err = v.UserIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_ip"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v GoogleValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v GoogleValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v GoogleValue) String() string {
	return "GoogleValue"
}

func (v GoogleValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"client_id":     basetypes.StringType{},
		"client_secret": basetypes.StringType{},
		"config_type":   basetypes.StringType{},
		"hosted_domain": basetypes.StringType{},
		"redirect_uri":  basetypes.StringType{},
		"refresh_token": basetypes.BoolType{},
		"user_ip":       basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"client_id":     v.ClientId,
			"client_secret": v.ClientSecret,
			"config_type":   v.ConfigType,
			"hosted_domain": v.HostedDomain,
			"redirect_uri":  v.RedirectUri,
			"refresh_token": v.RefreshToken,
			"user_ip":       v.UserIp,
		})

	return objVal, diags
}

func (v GoogleValue) Equal(o attr.Value) bool {
	other, ok := o.(GoogleValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ClientId.Equal(other.ClientId) {
		return false
	}

	if !v.ClientSecret.Equal(other.ClientSecret) {
		return false
	}

	if !v.ConfigType.Equal(other.ConfigType) {
		return false
	}

	if !v.HostedDomain.Equal(other.HostedDomain) {
		return false
	}

	if !v.RedirectUri.Equal(other.RedirectUri) {
		return false
	}

	if !v.RefreshToken.Equal(other.RefreshToken) {
		return false
	}

	if !v.UserIp.Equal(other.UserIp) {
		return false
	}

	return true
}

func (v GoogleValue) Type(ctx context.Context) attr.Type {
	return GoogleType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v GoogleValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"client_id":     basetypes.StringType{},
		"client_secret": basetypes.StringType{},
		"config_type":   basetypes.StringType{},
		"hosted_domain": basetypes.StringType{},
		"redirect_uri":  basetypes.StringType{},
		"refresh_token": basetypes.BoolType{},
		"user_ip":       basetypes.BoolType{},
	}
}
