// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_cluster

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ClusterDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time of the resources creation.",
				MarkdownDescription: "The date and time of the resources creation.",
			},
			"display_name": schema.StringAttribute{
				Computed:            true,
				Description:         "The common name of the Cluster resource.",
				MarkdownDescription: "The common name of the Cluster resource.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Flightdeck resource.",
				MarkdownDescription: "The ID of the Flightdeck resource.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Cluster resource.",
				MarkdownDescription: "The name of the Cluster resource.",
			},
			"region": schema.StringAttribute{
				Computed:            true,
				Description:         "The region where the Cluster is located.",
				MarkdownDescription: "The region where the Cluster is located.",
			},
		},
		Description: "Represents a Flightdeck Cluster resource.",
	}
}

type ClusterModel struct {
	CreatedAt   types.String `tfsdk:"created_at"`
	DisplayName types.String `tfsdk:"display_name"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Region      types.String `tfsdk:"region"`
}
