// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tenant_user

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TenantUserResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time of the resources creation.",
				MarkdownDescription: "The date and time of the resources creation.",
			},
			"email": schema.StringAttribute{
				Required:            true,
				Description:         "The email of the Tenant User.",
				MarkdownDescription: "The email of the Tenant User.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Flightdeck resource.",
				MarkdownDescription: "The ID of the Flightdeck resource.",
			},
			"organization_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Flightdeck Organization resource.",
				MarkdownDescription: "The ID of the Flightdeck Organization resource.",
			},
			"tenant_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Flightdeck Tenant resource.",
				MarkdownDescription: "The name of the Flightdeck Tenant resource.",
			},
			"username": schema.StringAttribute{
				Required:            true,
				Description:         "The username of the Tenant User.",
				MarkdownDescription: "The username of the Tenant User.",
			},
		},
		Description: "Represents a Tenant User resource.",
	}
}

type TenantUserModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	Email          types.String `tfsdk:"email"`
	Id             types.String `tfsdk:"id"`
	OrganizationId types.String `tfsdk:"organization_id"`
	TenantName     types.String `tfsdk:"tenant_name"`
	Username       types.String `tfsdk:"username"`
}
