// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tenant

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TenantResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time of the resources creation.",
				MarkdownDescription: "The date and time of the resources creation.",
			},
			"display_name": schema.StringAttribute{
				Required:            true,
				Description:         "The display name of the Tenant.",
				MarkdownDescription: "The display name of the Tenant.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Flightdeck resource.",
				MarkdownDescription: "The ID of the Flightdeck resource.",
			},
			"identifier": schema.StringAttribute{
				Computed:            true,
				Description:         "The internal identifier of the Tenant.",
				MarkdownDescription: "The internal identifier of the Tenant.",
			},
			"issuer_url": schema.StringAttribute{
				Computed:            true,
				Description:         "The URL of the Tenant's OIDC Issuer.",
				MarkdownDescription: "The URL of the Tenant's OIDC Issuer.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Tenant.",
				MarkdownDescription: "The name of the Tenant.",
			},
			"organization_id": schema.StringAttribute{
				Required: true,
			},
		},
		Description: "Represents a Tenant resource.",
	}
}

type TenantModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	DisplayName    types.String `tfsdk:"display_name"`
	Id             types.String `tfsdk:"id"`
	Identifier     types.String `tfsdk:"identifier"`
	IssuerUrl      types.String `tfsdk:"issuer_url"`
	Name           types.String `tfsdk:"name"`
	OrganizationId types.String `tfsdk:"organization_id"`
}
